FROM node:22.21.0 as build
WORKDIR /app
COPY ./ /app/

RUN npm install --registry https://registry.npmmirror.com
RUN sed -i 's|baseUrl: .*|baseUrl: ""|g' src/app/tokens/app-config.token.ts
RUN npm run build

FROM node:22.21.0-alpine

COPY --from=build /app/dist /app/dist/

WORKDIR /app
EXPOSE 4000

# ENV NODE_ENV production
ENTRYPOINT /usr/local/bin/node dist/note/server/server.mjs
