FROM node:22.21.0 as build
WORKDIR /app
COPY ./ /app/

RUN npm install --registry https://registry.npmmirror.com
RUN sed -i 's|baseUrl: .*|baseUrl: ""|g' src/app/tokens/app-config.token.ts
RUN npm run build

RUN gzip /app/dist/note/browser/*js && \
    gzip /app/dist/note/browser/*css
    #  && gzip /app/dist/blog/browser/*html

FROM nginx:1.29-alpine

COPY --from=build /app/dist/note/browser /usr/share/nginx/html

COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

RUN sed -i 's/worker_processes .*;/worker_processes 1;/' /etc/nginx/nginx.conf
